### ISSUE TITLE
tooltip code pulls backing item

### ISSUE THREAD

**Issue by zeptognome** [SpareSimian/BetterBagsItemDumper#1]
your tooltip example code pulls the tooltip for the backing item and not the actual owned item.
you shouldn't use this as backing items won't share the same states for anything useful to tooltip scan for.

at a minimum, use GetOwnedItemByID instead

or you can construct a C_Item starting with data.bagid and data.slotid

**Comment by JourneyOver** [comment]
Could this be a reason on why when I used this to try and dump my items in my bags that a ton of items just came up with `Retrieving item information` in the `leftText` no matter how many times I logged in and out?

**Comment by SpareSimian** [comment]
Thanks, I updated my Shadowlands plugin to use GetOwnedItemByID.

**Comment by JourneyOver** [comment]
Yeah, that definitely fixed the issues I was having in my plugin (It's going to be an AiO plugin that encompasses every expansion). By the way, thanks a bunch for your Shadowlands plugin. I took code from it and made my Profession Knowledge and Drakewatcher manuscript automatically add to the categories I had set for them, instead of adding things manually to my plugin lists as before. I also used your lootables code to create both a lootables category and a keystone category in my own plugin xD.

anyways this issue could probably be closed now I think :o

**Comment by SpareSimian** [comment]
I think we need a plugin registry so end users will know what's available.

I've already updated the Shadowlands addon and will update this example and then close this issue. I decided to break out the Lootable feature to its own plugin. Now I want to change the sort order and displayed section names so I can put my frequently-used sections at the end of the bag with short names. I proposed a callback for sorting and another for editing the final category name in one of the BB tickets.
